### ISSUE TITLE
Config options for purchasing?

### ISSUE THREAD

**Issue by Ryyye** [Szumi57/LethalInternship#15]
Options to configure the max number of interns you can have at once, as well as the cost per intern, would be lovely.
With that, a way to view the price in-game would be nice.
It may even be more elegant to just include them in the store (if this is easily doable)

**Comment by Szumi57** [comment]
Hi, thanks for your suggestions, configuration is very requested I definitely have to implement that soon :)
I need the separate menu for interns because there will be other options too (like cancel drop on moons without losing interns) and in the store it will be too messy , and conflicting with other mods, I already have enough work on this side ahah

**Comment by Ryyye** [comment]
Makes sense ! Just displaying the price in that menu would be appreciated then

**Comment by Szumi57** [comment]
Added config options with v0.15.0
