### ISSUE TITLE
Game crashing when 4th player is joining

### ISSUE THREAD

**Issue by clemlak** [Szumi57/LethalInternship#38]
Every time we had a 4th player joining us, the game immediately crashed. We tried disabling other mods or changing the host of the game but nothing changed.
Launching a game with only 3 players always worked though.
We're still playing on v56 by the way.

Edit: I just saw this commit https://github.com/Szumi57/LethalInternship/commit/b21aea99f2daa8f6ef2187b969e486ec8d060b23, will try out again and will let you know!

Edit 2: My friends and I REALLY love your mod, you did an amazing job!

**Comment by Szumi57** [comment]
Hi, thanks for reporting, yeah this bug is taken care of normally, but test conditions are hard for me to test... there's still a bug with more than 4 (with moreCompany mod) and maybe still with just 4 too...
Not crashing but things like the intern taking control of the 4th players camera and controls.
Anyway, don't hesitate to come back with your test results ! :)

**Comment by clemlak** [comment]
Hey! I played several games with 4 players + some interns and we had no issues, good job! :)
